-- ============================================================
-- LINES — MINIMAL DB CHANGES for Admin Console + Transactions
-- Run ONCE in Supabase Dashboard -> SQL Editor.
-- Uses the EXISTING tables (profiles, wallets, transactions,
-- notifications, balance_adjustments). Adds ONLY:
--   * helper function is_admin()  (reads profiles.is_admin)
--   * security-definer RPCs for user-submit / admin-approve flows
--   * RPCs so admins can read/edit users incl. auth metadata
--   * tightened RLS policies
-- ============================================================

-- ---------- 0. Admin predicate ----------
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS BOOLEAN
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND p.is_admin = TRUE
  );
$$;

-- Grant execute to authenticated users only (never anon)
REVOKE EXECUTE ON FUNCTION public.is_admin() FROM anon, public;
GRANT EXECUTE ON FUNCTION public.is_admin() TO authenticated;

-- ============================================================
-- 1. USER SUBMITS A TRANSACTION (deposit / withdraw) -> PENDING
--    id is generated by DB. Forces status='pending'. Rate limited.
-- ============================================================
CREATE OR REPLACE FUNCTION public.submit_transaction(
  p_type TEXT,
  p_amount_ugx NUMERIC,
  p_description TEXT DEFAULT NULL,
  p_payment_method TEXT DEFAULT NULL,
  p_recipient_info TEXT DEFAULT NULL
)
RETURNS public.transactions
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
DECLARE
  v_id TEXT;
  v_uid UUID := auth.uid();
  v_wallet public.wallets;
BEGIN
  IF v_uid IS NULL THEN RAISE EXCEPTION 'Not authenticated'; END IF;

  -- blocked accounts can't transact
  IF EXISTS (SELECT 1 FROM public.profiles WHERE id = v_uid AND status = 'blocked') THEN
    RAISE EXCEPTION 'Account is blocked';
  END IF;

  IF p_type NOT IN ('deposit', 'withdraw') THEN
    RAISE EXCEPTION 'Invalid transaction type';
  END IF;
  IF p_amount_ugx IS NULL OR p_amount_ugx <= 0 THEN
    RAISE EXCEPTION 'Amount must be greater than zero';
  END IF;

  -- withdrawals must not exceed available balance
  SELECT * INTO v_wallet FROM public.wallets WHERE user_id = v_uid FOR UPDATE;
  IF p_type = 'withdraw' THEN
    IF NOT FOUND THEN RAISE EXCEPTION 'Wallet not found'; END IF;
    IF p_amount_ugx > v_wallet.total_balance_ugx THEN
      RAISE EXCEPTION 'Insufficient balance: requested %, available %', p_amount_ugx, v_wallet.total_balance_ugx;
    END IF;
  END IF;

  v_id := 'tx_' || lower(substring(replace(gen_random_uuid()::text, '-', '') from 1 for 18));

  INSERT INTO public.transactions (
    id, user_id, type, amount_ugx, currency, status,
    description, payment_method, recipient_info, timestamp
  ) VALUES (
    v_id, v_uid, p_type, p_amount_ugx, 'UGX', 'pending',
    COALESCE(p_description, p_type), p_payment_method, p_recipient_info,
    (extract(epoch FROM now()) * 1000)::BIGINT
  );

  RETURN (SELECT t.* FROM public.transactions t WHERE t.id = v_id);
END;
$$;

REVOKE EXECUTE ON FUNCTION public.submit_transaction(TEXT, NUMERIC, TEXT, TEXT, TEXT) FROM anon, public;
GRANT EXECUTE ON FUNCTION public.submit_transaction(TEXT, NUMERIC, TEXT, TEXT, TEXT) TO authenticated;

-- ============================================================
-- 2. ADMIN: LIST PENDING TRANSACTIONS (with user info)
-- ============================================================
CREATE OR REPLACE FUNCTION public.admin_pending_transactions()
RETURNS TABLE (
  id TEXT, user_id UUID, username TEXT, user_full_name TEXT,
  type TEXT, amount_ugx NUMERIC, status TEXT,
  description TEXT, payment_method TEXT, recipient_info TEXT,
  created_at TIMESTAMPTZ
)
LANGUAGE sql SECURITY DEFINER SET search_path = public
AS $$
  SELECT t.id, t.user_id, p.username, p.full_name,
         t.type, t.amount_ugx, t.status,
         t.description, t.payment_method, t.recipient_info, t.created_at
  FROM public.transactions t
  JOIN public.profiles p ON p.id = t.user_id
  WHERE t.status = 'pending'
  ORDER BY t.created_at ASC;
$$;

-- ============================================================
-- 3. ADMIN: APPROVE TRANSACTION — atomic + idempotent.
--    Approved deposit -> credits wallet ONCE.
--    Approved withdraw -> debits wallet (funds reserved at submit).
--    Returns the new balance; NULL if already processed before.
-- ============================================================
CREATE OR REPLACE FUNCTION public.admin_approve_transaction(p_transaction_id TEXT)
RETURNS NUMERIC -- new wallet balance of the transaction owner
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
DECLARE
  v_uid UUID;
  v_type TEXT;
  v_amount NUMERIC;
  v_balance NUMERIC;
BEGIN
  IF NOT public.is_admin() THEN RAISE EXCEPTION 'Admin access required'; END IF;

  -- Lock the transaction row; only a row still 'pending' is processed.
  SELECT user_id, type, amount_ugx INTO v_uid, v_type, v_amount
  FROM public.transactions
  WHERE id = p_transaction_id AND status = 'pending'
  FOR UPDATE;

  IF NOT FOUND THEN
    RETURN NULL; -- already approved/rejected: NO double credit
  END IF;

  UPDATE public.transactions
  SET status = 'completed'
  WHERE id = p_transaction_id;

  SELECT total_balance_ugx INTO v_balance FROM public.wallets
  WHERE user_id = v_uid FOR UPDATE;

  IF v_type = 'deposit' THEN
    UPDATE public.wallets
    SET total_balance_ugx = total_balance_ugx + v_amount
    WHERE user_id = v_uid
    RETURNING total_balance_ugx INTO v_balance;
  ELSE -- withdraw: amount was never deducted at submit; deduct now on approval
    IF v_amount > COALESCE(v_balance, 0) THEN
      RAISE EXCEPTION 'Insufficient balance for withdrawal approval';
    END IF;
    UPDATE public.wallets
    SET total_balance_ugx = total_balance_ugx - v_amount
    WHERE user_id = v_uid
    RETURNING total_balance_ugx INTO v_balance;
  END IF;

  -- Notify user
  INSERT INTO public.notifications (id, user_id, title, message, read, type)
  VALUES (
    'notif_txappr_' || p_transaction_id, v_uid,
    CASE WHEN v_type = 'deposit' THEN 'Deposit Approved' ELSE 'Withdrawal Approved' END,
    CASE WHEN v_type = 'deposit'
      THEN 'Your deposit of UGX ' || v_amount::text || ' has been approved and credited to your balance.'
      ELSE 'Your withdrawal of UGX ' || v_amount::text || ' has been approved and settled.'
    END,
    false, 'success'
  ) ON CONFLICT (id) DO NOTHING;

  RETURN v_balance;
END;
$$;

-- ============================================================
-- 4. ADMIN: REJECT TRANSACTION — idempotent. Never touches balance.
-- ============================================================
CREATE OR REPLACE FUNCTION public.admin_reject_transaction(p_transaction_id TEXT)
RETURNS NUMERIC -- unchanged wallet balance
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
DECLARE
  v_uid UUID;
  v_amount NUMERIC;
  v_balance NUMERIC;
BEGIN
  IF NOT public.is_admin() THEN RAISE EXCEPTION 'Admin access required'; END IF;

  SELECT user_id, amount_ugx INTO v_uid, v_amount
  FROM public.transactions
  WHERE id = p_transaction_id AND status = 'pending'
  FOR UPDATE;

  IF NOT FOUND THEN RETURN NULL; END IF;

  UPDATE public.transactions SET status = 'rejected' WHERE id = p_transaction_id;

  SELECT total_balance_ugx INTO v_balance FROM public.wallets WHERE user_id = v_uid;

  INSERT INTO public.notifications (id, user_id, title, message, read, type)
  VALUES (
    'notif_txrej_' || p_transaction_id, v_uid,
    'Transaction Rejected',
    'Your request of UGX ' || v_amount::text || ' was rejected by an administrator. Your balance was not changed.',
    false, 'warning'
  ) ON CONFLICT (id) DO NOTHING;

  RETURN v_balance;
END;
$$;


-- ============================================================
-- 5. ADMIN: LIST ALL USERS (profiles + wallets + auth metadata)
--    Reads auth.users.email & raw_user_meta_data via definer rights.
-- ============================================================
CREATE OR REPLACE FUNCTION public.admin_list_users()
RETURNS TABLE (
  id UUID, username TEXT, full_name TEXT, phone TEXT,
  email TEXT, status TEXT, is_admin BOOLEAN,
  tier TEXT, referral_code TEXT, referral_count INTEGER,
  balance_ugx NUMERIC, active_machines_count INTEGER,
  transactions_count BIGINT,
  auth_created_at TIMESTAMPTZ, raw_user_meta_data JSONB
)
LANGUAGE sql SECURITY DEFINER SET search_path = public
AS $$
  SELECT p.id, p.username, p.full_name, p.phone,
         u.email, p.status, p.is_admin,
         p.tier, p.referral_code, p.referral_count,
         COALESCE(w.total_balance_ugx, 0),
         COALESCE(w.active_machines_count, 0),
         (SELECT COUNT(*) FROM public.transactions t WHERE t.user_id = p.id),
         u.created_at, u.raw_user_meta_data
  FROM public.profiles p
  JOIN auth.users u ON u.id = p.id
  LEFT JOIN public.wallets w ON w.user_id = p.id
  ORDER BY u.created_at ASC;
$$;

-- ============================================================
-- 6. ADMIN: UPDATE USER (profiles + wallets-visible fields + auth metadata)
-- ============================================================
CREATE OR REPLACE FUNCTION public.admin_update_user(
  p_user_id UUID,
  p_username TEXT DEFAULT NULL,
  p_full_name TEXT DEFAULT NULL,
  p_phone TEXT DEFAULT NULL,
  p_status TEXT DEFAULT NULL,
  p_full_name_meta TEXT DEFAULT NULL -- written to auth.users.raw_user_meta_data.full_name as well
)
RETURNS BOOLEAN
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
BEGIN
  IF NOT public.is_admin() THEN RAISE EXCEPTION 'Admin access required'; END IF;
  IF p_user_id IS NULL THEN RAISE EXCEPTION 'user id required'; END IF;

  UPDATE public.profiles SET
    username  = COALESCE(p_username, username),
    full_name = COALESCE(p_full_name, full_name),
    phone     = COALESCE(p_phone, phone),
    status    = COALESCE(p_status, status),
    updated_at = now()
  WHERE id = p_user_id;

  IF NOT FOUND THEN RAISE EXCEPTION 'User not found'; END IF;

  -- keep auth.users user_metadata in sync so it shows in Supabase Auth dashboard
  IF p_full_name_meta IS NOT NULL THEN
    UPDATE auth.users
    SET raw_user_meta_data = COALESCE(raw_user_meta_data, '{}'::jsonb) || jsonb_build_object('full_name', p_full_name_meta)
    WHERE id = p_user_id;
  END IF;

  RETURN TRUE;
END;
$$;

-- ============================================================
-- 7. ADMIN: BALANCE ADJUSTMENT — audited via existing balance_adjustments
-- ============================================================
CREATE OR REPLACE FUNCTION public.admin_adjust_balance(
  p_user_id UUID,
  p_amount NUMERIC,
  p_type TEXT,        -- 'add' | 'deduct'
  p_reason TEXT
)
RETURNS TABLE (previous_balance NUMERIC, new_balance NUMERIC)
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
DECLARE
  v_prev NUMERIC; v_new NUMERIC; v_me public.profiles%ROWTYPE;
BEGIN
  IF NOT public.is_admin() THEN RAISE EXCEPTION 'Admin access required'; END IF;
  IF p_type NOT IN ('add', 'deduct') THEN RAISE EXCEPTION 'Invalid adjustment type'; END IF;
  IF p_amount IS NULL OR p_amount <= 0 THEN RAISE EXCEPTION 'Amount must be positive'; END IF;

  SELECT * INTO v_me FROM public.profiles WHERE id = auth.uid();

  SELECT total_balance_ugx INTO v_prev FROM public.wallets WHERE user_id = p_user_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Wallet not found for user'; END IF;

  v_new := CASE WHEN p_type = 'add' THEN v_prev + p_amount ELSE v_prev - p_amount END;
  IF v_new < 0 THEN RAISE EXCEPTION 'Resulting balance cannot be negative'; END IF;

  UPDATE public.wallets SET total_balance_ugx = v_new, updated_at = now() WHERE user_id = p_user_id;

  INSERT INTO public.balance_adjustments (
    id, user_id, username, user_full_name,
    previous_balance_ugx, adjustment_amount_ugx, new_balance_ugx,
    type, reason, admin_id, admin_username, timestamp, date
  ) VALUES (
    'adj_' || replace(gen_random_uuid()::text, '-', ''), p_user_id,
    (SELECT username FROM public.profiles WHERE id = p_user_id),
    (SELECT full_name FROM public.profiles WHERE id = p_user_id),
    v_prev, p_amount, v_new, p_type, p_reason,
    auth.uid()::text, v_me.username,
    (extract(epoch FROM now()) * 1000)::BIGINT,
    to_char(now(), 'YYYY-MM-DD')
  );

  RETURN QUERY SELECT v_prev, v_new;
END;
$$;

-- ============================================================
-- GRANTS: every admin_* / submit function executed by authenticated only
-- ============================================================
DO $$
DECLARE f RECORD;
BEGIN
  FOR f IN
    SELECT p.proname, pg_get_function_identity_arguments(p.oid) AS args
    FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
    WHERE n.nspname = 'public'
      AND p.proname IN (
        'admin_pending_transactions','admin_approve_transaction','admin_reject_transaction',
        'admin_list_users','admin_update_user','admin_adjust_balance'
      )
  LOOP
    EXECUTE format('REVOKE EXECUTE ON FUNCTION public.%I(%s) FROM anon, public', f.proname, f.args);
    EXECUTE format('GRANT EXECUTE ON FUNCTION public.%I(%s) TO authenticated', f.proname, f.args);
  END LOOP;
END $$;

-- ============================================================
-- 8. INVESTMENT DEBIT (called by a user buying an investment node)
--    Deducts their OWN wallet only — no privileged access granted.
-- ============================================================
CREATE OR REPLACE FUNCTION public.apply_investment_debit(p_amount NUMERIC)
RETURNS NUMERIC -- new balance
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
DECLARE
  v_uid UUID := auth.uid();
  v_balance NUMERIC;
BEGIN
  IF v_uid IS NULL THEN RAISE EXCEPTION 'Not authenticated'; END IF;
  IF p_amount IS NULL OR p_amount <= 0 THEN RAISE EXCEPTION 'Amount must be positive'; END IF;

  SELECT total_balance_ugx INTO v_balance FROM public.wallets WHERE user_id = v_uid FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Wallet not found'; END IF;
  IF p_amount > v_balance THEN RAISE EXCEPTION 'Insufficient balance'; END IF;

  UPDATE public.wallets
  SET total_balance_ugx = total_balance_ugx - p_amount,
      active_machines_count = active_machines_count + 1,
      updated_at = now()
  WHERE user_id = v_uid
  RETURNING total_balance_ugx INTO v_balance;

  RETURN v_balance;
END;
$$;

REVOKE EXECUTE ON FUNCTION public.apply_investment_debit(NUMERIC) FROM anon, public;
GRANT EXECUTE ON FUNCTION public.apply_investment_debit(NUMERIC) TO authenticated;

-- ============================================================
-- RLS TIGHTENING on the EXISTING tables.
-- Replaces overly-permissive policies from the original schema dump
-- with safe ones (users own rows; admins get elevated access only
-- through the security-definer functions above).
-- ============================================================

-- TRANSACTIONS -------------------------------------------------
DROP POLICY IF EXISTS "Users can view their own transactions" ON public.transactions;
CREATE POLICY "tx_select" ON public.transactions FOR SELECT
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can insert their own transactions" ON public.transactions;
CREATE POLICY "tx_insert" ON public.transactions FOR INSERT
  WITH CHECK (auth.uid() = user_id AND status = 'pending');

DROP POLICY IF EXISTS "Users or admins can update transactions" ON public.transactions;
CREATE POLICY "tx_update_owner_pending_only" ON public.transactions FOR UPDATE
  USING (auth.uid() = user_id AND status = 'pending');

-- Status transitions to completed/rejected happen ONLY inside the
-- admin RPCs (security definer), never through direct table writes.

-- WALLETS ------------------------------------------------------
DROP POLICY IF EXISTS "Users can view their own wallet" ON public.wallets;
CREATE POLICY "wallet_select" ON public.wallets FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update their own wallet" ON public.wallets;
CREATE POLICY "wallet_update_admin_rpc_only" ON public.wallets FOR UPDATE
  USING (public.is_admin());

-- users can NEVER insert/delete wallets directly
DROP POLICY IF EXISTS "Users can manage their own machines" ON public.user_machines;
CREATE POLICY "machines_select" ON public.user_machines FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "machines_write_self" ON public.user_machines FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "machines_update_self" ON public.user_machines FOR UPDATE USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Notifications policies" ON public.notifications;
DROP POLICY IF EXISTS "Users can view and manage their own notifications" ON public.notifications;
CREATE POLICY "notif_select" ON public.notifications FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "notif_update_self" ON public.notifications FOR UPDATE USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Admin tasks viewable by admins and owners" ON public.admin_tasks;
CREATE POLICY "tasks_select" ON public.admin_tasks FOR SELECT USING (auth.uid() = user_id OR public.is_admin());

DROP POLICY IF EXISTS "Balance adjustments viewable by owner or admin" ON public.balance_adjustments;
CREATE POLICY "adjust_select" ON public.balance_adjustments FOR SELECT
  USING (auth.uid() = user_id::uuid OR public.is_admin());
